import styles from "../styles/Signup.module.css"
import Spinner from 'react-bootstrap/Spinner';
import uselogin from '@/customHooks/useLogin';
import Head from 'next/head'




const login = () => {

 const { setEmail,setPassword,onSubmitHandler,signpage,loader,loader2} =uselogin()

  return (
    <>
       <Head>
        <title>Wolf-Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sneaker.png" />
      </Head><main>
      <div className={styles.container}>
      <div className={styles.card}>
        <br/>
        <br/>
        <br/>

        <h1 className={styles.hcentre}>Login</h1>
        <br/>
        <br/>
        <div className={styles.hcentre}>
          <div className={styles.inputgroup}>
            <label className={styles.label}>Email address</label>
            <input
              onChange={(e) => setEmail(e.target.value)}
              type="email"
              name="Email"
              className={styles.input}
              id="email"
              placeholder="Enter your email" />
          </div>
        </div>
        <div className={styles.hcentre} >
          <div className={styles.inputgroup}>
            <label className={styles.label}>Password</label>
            <input
              onChange={(e) => setPassword(e.target.value)}
              type="password"
              name="password"
              className={styles.input}
              id="Password"
              placeholder="Enter your Password" />
          </div>
        </div>
        <div className={styles.hcentre}> 
        {loader ?
          <button onClick={onSubmitHandler} className={styles.button} >Login</button>:<Spinner  animation="border" role="status"/>}
          {loader2 ?
          <button onClick={signpage}  className={styles.button} >Signup with us</button>:<Spinner  animation="border" role="status"/>}
        </div>
      </div>
    </div></main></>
  
  )
}

export default login