import React from 'react'
import styles from "../styles/Signup.module.css"
import Spinner from 'react-bootstrap/Spinner';
import Head from 'next/head'
import useSignup from '@/customHooks/useSignup';

const Signup = () => {

  const { onSubmitHandler, loginpage, loader, setusername, setemail, setpassword } = useSignup()

  return (
    <>
      <Head>
        <title>Wolf-Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sneaker.png" />
      </Head><main>
        <div className={styles.container}>
          <div className={styles.card}>
            <br />
            <br />
            <br />
            <h1 className={styles.hcentre}>Sign up</h1>
            <br />
            <br />
            <div className={styles.hcentre}>
              <div className={styles.inputgroup}>
                <label className={styles.label}>username</label>
                <input
                  onChange={(e) => setusername(e.target.value)}
                  type="text"
                  placeholder="Enter your name"
                  className={styles.input}
                  id="Username"
                />
              </div>
            </div>
            <br />
            <div className={styles.hcentre}>
              <div className={styles.inputgroup}>
                <label className={styles.label}>Email address</label>
                <input
                  onChange={(e) => setemail(e.target.value)}
                  type="email"
                  id="Email"
                  className={styles.input}
                  placeholder="Enter your email" />
              </div>
            </div>
            <br />
            <div className={styles.hcentre}>
              <div className={styles.inputgroup}>
                <label className={styles.label} >Password</label>
                <input
                  onChange={(e) => setpassword(e.target.value)}
                  type="password"
                  name="password"
                  className={styles.input}
                  id="Password"
                  placeholder="Enter your Password" />
              </div>
            </div>
            <br />
            <div className={styles.hcentre}>
              {loader ?
                <button onClick={onSubmitHandler} className={styles.button} >Sigin up</button> : <Spinner animation="border" role="status" />}
              <button onClick={loginpage} className={styles.button} >Already logged In </button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
export default Signup