import Storecom from '@/components/Storecom/Storecom'
import Head from 'next/head'

const Store = () => {
  return (
    <>
      <Head>
        <title>Wolf-Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sneaker.png" />
      </Head><main>
        <div>
          <Storecom />
        </div>
      </main>
    </>
  )
}

export default Store